language: java
notifications:
  hipchat:
    rooms:
      secure: RzdS3EMrKbzK0FrRuxBSVTBS6Xaxy5yHJePfYB4FnRdHoUin/dwYH2Xke+i9k16MR6OvIEPIsoL16aRmPQ2rATijYplFuYJm2g/GLMGM5hraLTt/bDxGC9ddOa833y4JECdSOoHTdtkjgoWHZ4N7w9z7nYhesPXapP0y+en0Ys2ioJNzDF3zyJG8TZOVewbuq4EKxV+aCqLzpemC+6IdnPj6TZFQ5dBtAIkzE2+pyRbdjpJjOJZRvqE1qJB82U9eD7566nvt54vYUBfP6L3v1icUe2e1hWrBTircMeE+VlFK/eaGocT8CBO2tOMYBQxDdgNfurcnsRi+ER2nRo3AyKNy8HcjJyx04dasSg4Qj7q09vd6sHcmFtU8TaffhlXdeuFRqLdJ7ybXBtRqIm4+5AzYEYTCYrAdNOVlLlYnSp/veNgXFW9PehSw3g3NDKobzvZjfhFd/mTgW21LF1skaSG1vcs/DzNExR8iw6EAonM+7IYNMiJBUyLvRvHqZ+2aqGcP+iyPKAjxgHDousdMS2GcqoYJ2QCMIV+MclPcMRiBwl6GTOsAqTz11wgchSJJpcG/A1xUgPgMuLL8pIIoLlfxrvY609nEOcnAdXU/YjRsJ4SWn7DE1RQnJfNHEpqiLNzpxoIKIFx+nSlq8BjHoIRXaep5norsS//QrRNQXok=
deploy:
  provider: releases
  api_key:
    secure: E7pdaTj8eEajayvwv8A1iTshU30F2Tebkp8tODfK4JrIfljaEvx+PCigz3zYCdhA/bi1AJ/TgNgepEBqiEMk2IXao8RAamNe/x9G0UYViN25jPUU+QXDEGDaGOUIqq40xCNzKCnOPvZp/M7T1P2gDRkzDh6v5NZZyh98J7D0m1iuXikFmu+Z/RVYPB6vCUDzAN9PRMtHXYb1tHvCZw/SWroYROwPdCsLi/KA8Nb7wRv/So6rQ1fTxPCUieJM9p1ZXem2nWzOm6QDAvzwdGG23hm2PE7zUlFsxBPAof5dD0MeWTAsG9Uc/QXQqrC5PQmPqCczij1kat7++PhNnUGcOt95V2vjQaIDpv9XaZC5ndUyHaquakMqexhR6xVfocD4XY6Ao5TGLfxFfDg/M4bP+LrvPnw+9DRPRippFfEuv/LViFt5INn4RABitnQavSb7NiuRXFPhk0ANzQEHWfU9AcNNb1rEO4OL5HF0pecAA7rL9LRKtFHIfjKmZyepR6oyJUWKy9AjSSEV4OekTfTH4BGhRRGIaXn6hISiVYM2UZU61X/Evz0qPJhEun7yRMOwaAwP/wla1fVRP3oDdwLCDGmt0hPAdjlNIcD0jfkZjCtqJ5aHTuV2+TIXjseaE+HYuhHQaxaZC7/OIKWGRb2iqXZG6mgwbUVwCG+46ethxqw=
  file: build/libs/xlr-saucelabs-plugin-1.0.0.RC1.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-saucelabs-plugin
